### ISSUE TITLE
Support DMA Settings for Google

### ISSUE THREAD

**Issue by fealXX** [Tealium/tealium-ios-adjust-remote-command#7]
Hi!

To use the Google Ads Integration of Adjust in the EEA it will be mandatory to pass granular options to the thirdpartysharing Function in the future, because of the Digital Markets Act. 
https://help.adjust.com/en/article/privacy-features-ios-sdk#provide-consent-data-to-google-digital-markets-act-compliance

Currently the remote command module only supports boolean value, so adding support for addGranularOption would be highly appreciated :)

All the best,

Felix

**Comment by jameskeith** [comment]
@fealXX  - as mentioned on the equivalent Android ticket, this has now been release also for iOS as [v1.2.0](https://github.com/Tealium/tealium-ios-adjust-remote-command/releases/tag/1.2.0)

Let me know if you have further queries
