### ISSUE TITLE
Update tealium-swift dependency >= 2.12 to support XCode15

### ISSUE THREAD

**Issue by fealXX** [Tealium/tealium-ios-adjust-remote-command#9]
Hi!

Since XCode15 dropped support for iOS 11 it currently cannot be used for Versions of the tealium-swift dependency before 2.12.0 (see [Release Notes for 2.11](https://github.com/Tealium/tealium-swift/releases/tag/2.11.0)). Starting latest April, Apple will require us to use XCode15, therefore we'd really appreciate a new release that targets a current version of tealium-swift.

[MT-1344 seems to be related to this.](https://github.com/Tealium/tealium-flutter/compare/master...mt-1344)

Thanks,

Felix

**Comment by craigrouse** [comment]
@fealXX Thanks for opening this. We are actively working on updating all our projects to target iOS 12/Xcode 15. This will be completed soon.
